# Generated by Django 3.0.4 on 2020-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roaster', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('variety', models.CharField(max_length=50)),
                ('brew_method', models.CharField(max_length=50)),
                ('tasting_notes', models.TextField(default='Red fruits, berries, etc.')),
            ],
        ),
    ]
